### ISSUE TITLE
WebAuthentication: Tracking Issue

### ISSUE THREAD

**Issue by sejr** [sejr/swift-authentication#4]
This issue tracks features for the WebAuthentication module.

## HTTP Basic Authentication

- [ ] Process Basic authorization in an HTTP request
- [ ] Generate Basic authentication challenges 

## HTTP Digest Authentication

- [ ] Process Digest authorization in an HTTP request
- [ ] Generate Digest authentication challenges

## Web Authentication API

- [ ] WebAuthenticationService protocol definition: adds function to register new credentials
- [ ] Web credential: Password
- [ ] Web credential: Federated
- [ ] Web credential: Public key

## OAuth2 + OpenID Connect

- [ ] Token endpoint (support client credentials or authorization code)
- [ ] Well known / JWKS support, key rotation (introduces dep on storage mechanism for keys)
- [ ] UserInfo endpoint
- [ ] Discovery
- [ ] Dynamic client registration

## Vapor support

Vapor obviously has [extensive authentication support](https://docs.vapor.codes/4.0/authentication/) already; it will be important for this module to compliment that work.

**Comment by karimhm** [comment]
[`OAuth 2.1`](https://oauth.net/2.1/) might be a thing that worth consideration.

**Comment by sejr** [comment]
@karimhm Definitely! I do still want to be able to correctly support providers that rely on legacy flows (with appropriate warnings), but generally will include everything necessary for 2.1 compliance.
